"""Pydantic models and TypedDict state for the agent system.

Defines data contracts for agent workflows, including the
LangGraph state, task plans, code output, and review results.
"""

from __future__ import annotations

from typing import Any, TypedDict

from pydantic import BaseModel, ConfigDict, Field

# ---------------------------------------------------------------------------
# LangGraph workflow state
# ---------------------------------------------------------------------------


class AgentState(TypedDict, total=False):
    """Typed state passed through the LangGraph workflow.

    Each agent node reads from and writes to this shared state.

    Attributes:
        goal: The developer's original request.
        context_results: Relevant memories from vector search.
        graph_context: Related entities/relationships from Neo4j.
        plan: Generated task plan.
        code_outputs: Generated code snippets.
        review: Review results from the reviewer agent.
        iteration: Current review-loop iteration count.
        max_iterations: Maximum allowed review-loop iterations.
        final_response: The final assembled response to return.
        error: Error message if workflow fails.
    """

    goal: str
    context_results: list[dict[str, Any]]
    graph_context: dict[str, Any]
    plan: dict[str, Any]
    code_outputs: list[dict[str, Any]]
    review: dict[str, Any]
    iteration: int
    max_iterations: int
    final_response: str
    error: str


# ---------------------------------------------------------------------------
# API request / response models
# ---------------------------------------------------------------------------


class AgentRequest(BaseModel):
    """Request model for agent workflow endpoints.

    Attributes:
        goal: The developer's goal or feature request.
        entity_name: Optional entity for graph context lookup.
        max_iterations: Max review-loop iterations.
    """

    model_config = ConfigDict(frozen=True)

    goal: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="Developer goal or feature request",
    )
    entity_name: str | None = Field(
        default=None,
        description="Optional entity name for graph context",
    )
    max_iterations: int = Field(
        default=3,
        ge=1,
        le=10,
        description="Max review-loop iterations",
    )


class TaskStep(BaseModel):
    """A single step in a task plan.

    Attributes:
        step_number: Order in the plan.
        description: What this step accomplishes.
        details: Optional additional details.
    """

    model_config = ConfigDict(frozen=True)

    step_number: int = Field(..., description="Step order")
    description: str = Field(..., description="Step description")
    details: str = Field(default="", description="Additional details")


class TaskPlan(BaseModel):
    """A development plan generated by the planner agent.

    Attributes:
        goal: The original developer goal.
        steps: Ordered list of task steps.
        architecture_notes: Optional architecture observations.
    """

    model_config = ConfigDict(frozen=True)

    goal: str = Field(..., description="Original developer goal")
    steps: list[TaskStep] = Field(
        default_factory=list,
        description="Ordered task steps",
    )
    architecture_notes: str = Field(
        default="",
        description="Architecture observations or recommendations",
    )


class CodeOutput(BaseModel):
    """Code generated by the developer agent.

    Attributes:
        filename: Suggested filename for the code.
        language: Programming language.
        code: The generated source code.
        explanation: What this code does.
    """

    model_config = ConfigDict(frozen=True)

    filename: str = Field(..., description="Suggested filename")
    language: str = Field(default="python", description="Programming language")
    code: str = Field(..., description="Generated source code")
    explanation: str = Field(default="", description="What this code does")


class ReviewIssue(BaseModel):
    """A single issue found during code review.

    Attributes:
        severity: Issue severity — 'critical', 'warning', 'suggestion'.
        description: What the issue is.
        suggestion: How to fix it.
    """

    model_config = ConfigDict(frozen=True)

    severity: str = Field(
        ...,
        pattern="^(critical|warning|suggestion)$",
        description="Issue severity",
    )
    description: str = Field(..., description="Issue description")
    suggestion: str = Field(default="", description="Fix suggestion")


class ReviewResult(BaseModel):
    """Review output from the reviewer agent.

    Attributes:
        approved: Whether the code passes review.
        issues: List of discovered issues.
        summary: Overall review summary.
    """

    model_config = ConfigDict(frozen=True)

    approved: bool = Field(..., description="Whether code passes review")
    issues: list[ReviewIssue] = Field(
        default_factory=list,
        description="Discovered issues",
    )
    summary: str = Field(default="", description="Overall review summary")


class AgentResponse(BaseModel):
    """Response model for agent workflow endpoints.

    Attributes:
        goal: The original goal.
        plan: The generated task plan.
        code_outputs: Generated code snippets.
        review: Review results.
        final_response: The assembled final answer.
        iterations_used: How many review loops were needed.
    """

    model_config = ConfigDict(frozen=True)

    goal: str = Field(..., description="Original goal")
    plan: TaskPlan | None = Field(default=None, description="Task plan")
    code_outputs: list[CodeOutput] = Field(
        default_factory=list,
        description="Generated code",
    )
    review: ReviewResult | None = Field(default=None, description="Review result")
    final_response: str = Field(default="", description="Final assembled answer")
    iterations_used: int = Field(default=1, description="Review loop iterations used")
